//
//  MovieListPresenterTests.swift
//  MovieSelector
//
//  Created by Cagdas Timurlenk on 23.09.2018.
//  Copyright (c) 2018 CodeAndDreams. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MovieSelector
import XCTest

class MovieListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMovieListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieListPresenter()
  {
    sut = MovieListPresenter()
  }
  
  // MARK: Test doubles
  
//  class MovieListDisplayLogicSpy: MovieListDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: MovieList.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = MovieListDisplayLogicSpy()
//    sut.viewController = spy
//    let response = MovieList.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
}
